![](../img/banner_day1.png)

<br>

# 1일차 실습(2) - 넘파이(NumPy)

<br>
<br>
<div align='right'>강사 성민석</div>
<div align='right'>고려대학교 인공지능학과 박사과정</div>
<div align='right'>(minsuksung@korea.ac.kr)</div>

> <font color='red'><b>WARNING</b></font>: 본 컨텐츠는 **[저작권법 제25조 제2항](https://glaw.scourt.go.kr/wsjo/lawod/sjo192.do?contId=2135829&jomunNo=25)** 에 의해 강의 목적으로 이용한 저작물이 포함되어 있습니다.  
> 해당 자료를 제작자의 동의없이 <font color='red'><b>외부에 임의로 공개 및 수정하는 것을 금지</b></font>하며 이를 위반하는 경우 저작권 침해로서 관련법에 따라 처벌될 수 있으니 주의해주시기 바랍니다.

<h1>목차<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#NumPy-불러오기" data-toc-modified-id="NumPy-불러오기-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>NumPy 불러오기</a></span></li><li><span><a href="#np.array" data-toc-modified-id="np.array-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>np.array</a></span></li><li><span><a href="#연산" data-toc-modified-id="연산-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>연산</a></span></li><li><span><a href="#다차원-array" data-toc-modified-id="다차원-array-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>다차원 array</a></span></li><li><span><a href="#indexing-&amp;-slicing" data-toc-modified-id="indexing-&amp;-slicing-5"><span class="toc-item-num">5&nbsp;&nbsp;</span>indexing &amp; slicing</a></span></li><li><span><a href="#Broadcasting" data-toc-modified-id="Broadcasting-6"><span class="toc-item-num">6&nbsp;&nbsp;</span>Broadcasting</a></span></li><li><span><a href="#reshape" data-toc-modified-id="reshape-7"><span class="toc-item-num">7&nbsp;&nbsp;</span>reshape</a></span></li><li><span><a href="#참고자료" data-toc-modified-id="참고자료-8"><span class="toc-item-num">8&nbsp;&nbsp;</span>참고자료</a></span></li></ul></div>

## NumPy 불러오기
<hr style="height:5px;border:none;color:#132e4f;background-color:#132e4f;"/>

<div style="background:rgb(255,135,0,0.1);padding:20px;margin: 20px;color:black;">
    <b>설명</b>
    <ul>
        <li>ㅇㅇㅇㅇㅇ</li>
    </ul>
</div>

In [1]:
import numpy as np

## np.array
<hr style="height:5px;border:none;color:#132e4f;background-color:#132e4f;"/>

In [3]:
x = np.array([1,2,3])
print(x)

[1 2 3]


In [4]:
type(x)

numpy.ndarray

In [5]:
x2 = [1,2,3]
print(x2)

[1, 2, 3]


In [6]:
type(x2)  # list와 확실히 다르다

list

In [14]:
# list 에서 활용할 수 있는 함수들
dir(x2)

['__add__',
 '__class__',
 '__contains__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__reversed__',
 '__rmul__',
 '__setattr__',
 '__setitem__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'append',
 'clear',
 'copy',
 'count',
 'extend',
 'index',
 'insert',
 'pop',
 'remove',
 'reverse',
 'sort']

In [15]:
dir(x)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__

## 연산
<hr style="height:5px;border:none;color:#132e4f;background-color:#132e4f;"/>

In [16]:
x1 = np.array([1,2,3])
x2 = np.array([4,5,6])

In [17]:
x1 + x2  # 기본적으로 연산은 element-wise

array([5, 7, 9])

In [19]:
x1 - x2

array([-3, -3, -3])

In [20]:
x1 * x2

array([ 4, 10, 18])

In [21]:
x1 / x2

array([0.25, 0.4 , 0.5 ])

## 다차원 array
<hr style="height:5px;border:none;color:#132e4f;background-color:#132e4f;"/>

In [22]:
x1 = np.array([
    [1,2,3],
    [4,5,6]
])

In [23]:
x1

array([[1, 2, 3],
       [4, 5, 6]])

In [24]:
x1.shape

(2, 3)

In [25]:
x1.dtype

dtype('int64')

In [26]:
x2 = np.array([
    [7,8,9],
    [10,11,12]
])

In [27]:
x2

array([[ 7,  8,  9],
       [10, 11, 12]])

In [28]:
x1 + x2

array([[ 8, 10, 12],
       [14, 16, 18]])

In [29]:
x1 * x2

array([[ 7, 16, 27],
       [40, 55, 72]])

In [30]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
np.zeros((10,))

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [32]:
np.ones((10,))

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [41]:
np.random.randint(0,10,size=(10,))

array([3, 3, 0, 6, 5, 3, 5, 2, 6, 9])

In [42]:
np.random.randn(3,3)

array([[ 0.01397821, -0.86593005, -0.45775037],
       [-1.00913813,  0.51406832,  0.73899052],
       [-0.09857543,  1.96542792,  0.57132338]])

## indexing & slicing
<hr style="height:5px;border:none;color:#132e4f;background-color:#132e4f;"/>

In [44]:
x1 = np.array([
    [1,2,3],
    [4,5,6]
])

In [45]:
x1[0]

array([1, 2, 3])

In [46]:
x1[0][1]

2

In [47]:
x1[0,1]

2

In [50]:
x1[1,0:2]

array([4, 5])

## Broadcasting
<hr style="height:5px;border:none;color:#132e4f;background-color:#132e4f;"/>

In [51]:
x1 = np.array([
    [1,2,3],
    [4,5,6]
])

In [52]:
x2 = np.array([
    [1,2,3],
])

In [53]:
x1 + x2

array([[2, 4, 6],
       [5, 7, 9]])

In [54]:
x1 * x2

array([[ 1,  4,  9],
       [ 4, 10, 18]])

## reshape
<hr style="height:5px;border:none;color:#132e4f;background-color:#132e4f;"/>

In [55]:
x1 = np.array([
    [1,2,3],
    [4,5,6]
])

In [56]:
x1

array([[1, 2, 3],
       [4, 5, 6]])

In [57]:
x1.shape

(2, 3)

In [58]:
x1.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [60]:
x1.reshape(1,6)

array([[1, 2, 3, 4, 5, 6]])

In [61]:
x1.reshape(6,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [62]:
x1.reshape(1,2,3)

array([[[1, 2, 3],
        [4, 5, 6]]])

## 참고자료
<hr style="height:5px;border:none;color:#132e4f;background-color:#132e4f;"/>

- http://bigdata.dongguk.ac.kr/lectures/Python/_book/numpy.html

<br>

<span style="color:rgb(120, 120, 120)">본 학습 자료를 포함한 모든 자료의 저작권은 성민석에 있으며 제작자의 동의없이 외부로의 무단 복제, 배포 및 전송을 절대로 불허합니다.

<b>Copyright ⓒ 2022. Minsuk Sung. All rights reserved.</b>
</span>

<br>